apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-sa
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-objectstorage-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.objectstorageController.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: container-object-storage-interface-controller
      app.kubernetes.io/part-of: container-object-storage-interface
      app.kubernetes.io/version: main
    {{- include "container-object-storage-interface-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: container-object-storage-interface-controller
        app.kubernetes.io/part-of: container-object-storage-interface
        app.kubernetes.io/version: main
      {{- include "container-object-storage-interface-controller.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --v=5
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.objectstorageController.objectstorageController.image.repository
          }}:{{ .Values.objectstorageController.objectstorageController.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.objectstorageController.objectstorageController.imagePullPolicy
          }}
        name: objectstorage-controller
        resources: {}
      serviceAccountName: {{ include "container-object-storage-interface-controller.fullname"
        . }}-sa