apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-objectstorage-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-objectstorage-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "container-object-storage-interface-controller.fullname" . }}-objectstorage-controller'
subjects:
- kind: ServiceAccount
  name: '{{ include "container-object-storage-interface-controller.fullname" . }}-sa'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-objectstorage-controller
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "container-object-storage-interface-controller.fullname" . }}-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "container-object-storage-interface-controller.fullname" . }}-sa'
  namespace: '{{ .Release.Namespace }}'