apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "container-object-storage-interface-controller.fullname" . }}-role
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: container-object-storage-interface
  {{- include "container-object-storage-interface-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - bucketclaims
  - bucketaccesses
  - bucketclaims/status
  - bucketaccesses/status
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - buckets
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - bucketclasses
  - bucketaccessclasses
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - list
  - get